//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AngularEmployeeService
{
    using System;
    using System.Collections.Generic;
    
    public partial class AngularEmployee
    {
        public string code { get; set; }
        public string name { get; set; }
        public string Gender { get; set; }
        public string contactPreference { get; set; }
        public string email { get; set; }
        public string dateOfBirth { get; set; }
        public Nullable<int> department { get; set; }
        public Nullable<bool> isActive { get; set; }
        public string photoPath { get; set; }
    }
}
